# Используем базовый образ с Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем все необходимые зависимости для линтинга и тестов
RUN pip install --no-cache-dir flake8 pylint pytest pytest-asyncio sqlalchemy pydantic asyncpg

# Копируем все файлы проекта в контейнер
COPY . .
ENV PYTHONPATH="/app/src"
# Выполняем линтинг и тесты
CMD flake8 ./src/models ./src/storage tests && pytest tests/test_repo.py --asyncio-mode=auto

RUN pytest tests