services:
    app:
        container_name: app
        build:
            context: ../
            dockerfile: ./Dockerfile
        restart: always
        ports: 
            - "3012:3012"
        networks:
            - postgres-db
            - appnet


    postgres:
        container_name: PgDBRegSysEvents
        hostname: postgres
        image: postgres:17.4-alpine3.20
        env_file:
            - db.env
        ports:
            - "5434:5432"
        volumes:
            - dataRegSysEvents:/var/lib/postgresql/regSysEvents/data
        networks:
            - postgres-db
            - appnet

volumes:  
    dataRegSysEvents: 

networks:
    postgres-db:
        name: postgres-db
    appnet:
        name: appnet