services:
    postgres:
        container_name: PgDBRegSysEvents
        hostname: postgres
        image: postgres:17.4-alpine3.20
        env_file:
            - db.env
        ports:
            - "5434:5432"
        volumes:
            - dataRegSysEvents:/var/lib/postgresql/regSysEvents/data
        networks:
            - postgres-db
            - appnet

volumes:  
    dataRegSysEvents: 

networks:
    postgres-db:
        name: postgres-db
    appnet:
        name: appnet